// playgrounds/angular/src/main.ts
import { bootstrapApplication } from '@angular/platform-browser';
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import '@arc-web/components/src/components/container/arc-container';

@Component({
  standalone: true,
  selector: 'app-root',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-container><arc-container>`,
})
export class AppComponent { }

bootstrapApplication(AppComponent).catch(console.error);

// playgrounds/lit/src/main.ts
import '@arc-web/components/themes/index.css';

import { html, LitElement } from 'lit';
import { customElement } from 'lit/decorators.js';
import '@arc-web/components/src/components/container/arc-container';

@customElement('app-root')
export class AppComponent extends LitElement {
  render() {
    return html`<arc-container></arc-container>`;
  }
}
