// playgrounds/vue/src/app.vue
<template>
  <arc-container>
    <arc-navbar slot="nav" logo="assets/arc-red.svg" tabs="0">
      <span slot="name">ARC Playground</span>

      <arc-icon-button label="Home" name="home" />
      <arc-icon-button label="Settings" name="settings" />

      <arc-sso
        slot="user"
        client-id="b4a4c03f-4915-42db-aa79-d49a650974c2"
        tenant-id="4ae48b41-0137-4599-8661-fc641fe77bea"
      />
    </arc-navbar>

    <section id="playground" />
  </arc-container>
</template>

// playgrounds/react/src/app.tsx
import React from 'react';
import {
  ArcContainer,
  ArcNavbar,
  ArcIconButton,
  ArcSSO,
} from '@arc-web/react';

export function App() {
  return (
    <ArcContainer>
      <ArcNavbar slot="nav" logo="assets/arc-red.svg" tabs={0}>
        <span slot="name">ARC Playground</span>

        <ArcIconButton label="Home" name="home"></ArcIconButton>
        <ArcIconButton label="Settings" name="settings"></ArcIconButton>

        <ArcSSO
          slot="user"
          client-id="b4a4c03f-4915-42db-aa79-d49a650974c2"
          tenant-id="4ae48b41-0137-4599-8661-fc641fe77bea"
        ></ArcSSO>
      </ArcNavbar>

      <section id="playground"></section>
    </ArcContainer>
  );
}
