// playgrounds/lit/src/main.ts
import '@arc-web/components/themes/index.css';

import { html, LitElement } from 'lit';
import { customElement } from 'lit/decorators.js';
import '@arc-web/components/src/components/container/arc-container';

@customElement('app-root')
export class AppComponent extends LitElement {
  render() {
    return html`<arc-container></arc-container>`;
  }
}

// playgrounds/react/src/main.tsx
import React from 'react';

import '@arc-web/components/themes/index.css';
import '@arc-web/components/themes/light.css';
import '@arc-web/components/themes/dark.css';

import { createRoot } from 'react-dom/client';
import { App } from './app';

createRoot(document.createElement('app-root')).render(<App />);
